### ISSUE TITLE
Setup Kanban board 

### ISSUE THREAD

**Issue by ogagaoghene** [ogagaoghene/recipe_app#5]
The link to thE gItHub KanBan board
https://github.com/users/ogagaoghene/projects/7
https://github.com/users/ogagaoghene/projects/7

I am the only one assigned to this Group Project. I have been asked to let the reviewer know about this. Please find below screenshots of the conversations I had with a representative of Microverse that advised that I take a screenshot of our conversation.

![image](https://user-images.githubusercontent.com/30408871/203043528-db0f7693-c556-4800-b0ef-b9a4ff65c4ad.png)
![image](https://user-images.githubusercontent.com/30408871/203043359-1609b365-a8bf-447e-b6a7-38cd91f92785.png)

The link to thE gItHub KanBan board
https://github.com/users/ogagaoghene/projects/7
https://github.com/users/ogagaoghene/projects/7

**Comment by prolajumokeoni** [comment]
Hi @ogagaoghene 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a link to your GitHub project(kanban board)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ogagaoghene,

Good job so far!
✔️ Good documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your tasks do not have descriptions. Kindly ensure all your tasks have descriptions

  ![didoe](https://user-images.githubusercontent.com/36542986/203057245-810d2704-949a-4c9e-ac2a-93c4ea95e8ae.jpg)

- [x] You are missing most of the tasks. You only have the registration and food list tasks. Kindly include the remaining tasks as listed in the requirements.

  List of requirements | Your tasks
  :---:|:---:
  ![eyu](https://user-images.githubusercontent.com/36542986/203056961-3d50e8a5-0599-41e7-bcfe-4dc88e98e347.jpg) | ![urie](https://user-images.githubusercontent.com/36542986/203056946-eebe106e-8564-4019-bb55-4abfc5f3a851.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ogagaoghene,

Good job so far!
✔️ Good documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your tasks do not have descriptions. Kindly ensure all your tasks have descriptions

  ![didoe](https://user-images.githubusercontent.com/36542986/203057245-810d2704-949a-4c9e-ac2a-93c4ea95e8ae.jpg)

- [ ] You are missing most of the tasks. You only have the registration and food list tasks. Kindly include the remaining tasks as listed in the requirements.

  List of requirements | Your tasks
  :---:|:---:
  ![eyu](https://user-images.githubusercontent.com/36542986/203056961-3d50e8a5-0599-41e7-bcfe-4dc88e98e347.jpg) | ![urie](https://user-images.githubusercontent.com/36542986/203056946-eebe106e-8564-4019-bb55-4abfc5f3a851.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ogagaoghene** [comment]
@TedLivist  I am the only one in my team. Attached in this issue request is my correspondence with a staff of Microverse. She asked I make this known to you. Don't you think it will be fair that specific requirements be assigned to me. I saw the list of requirements that you have attached. Kindly advise and be discretional as I am the only one in my team. I look forward to hearing from you so I can initiate the next step.

**Comment by ogagaoghene** [comment]
@TedLivist The screenshoted list of requirements is for a team of 3 members. Kindly specify what is appropriate for me as advised by the staff of Microverse. That's what is fair

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @ogagaoghene, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [x] In the attached video below you can see that I have shown that there should be a column between `In Progress `and `Done` which is "In Review".
- [x] Also make sure to add a description inside the card example Card title should be "Recipes list" and the description is "Recipes list should display a list of recipes created by the logged-in user and should lead to recipe details. If the user is the owner of the recipe, it should allow the user to delete it." Make sure to make changes according to the example for all.

https://user-images.githubusercontent.com/70269507/203099956-39323a9b-f9c1-4b12-8d09-0b31ffa11da9.mov

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danmainah** [comment]
Hi @ogagaoghene , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Good documentation
✔️ Good descriptions

 # Required Changes ♻️

- [x] @ogagaoghene great work implementing the changes requested but you forgot one small change, to add a description to  one task as shown below:
![image](https://user-images.githubusercontent.com/61408860/203136300-ac1ead52-856a-4ccd-9ac3-ff44a9f73dcf.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ogagaoghene** [comment]
@danmainah I have exhaused all reviews. How can I request for an extra review. You should have optionally mentioned this bro. That is what is expected.

**Comment by danmainah** [comment]
> @danmainah I have exhaused all reviews. How can I request an extra review. You should have optionally mention this bro. That is what is expected. 

I understand the frustration but I cannot approve it if all requirements are not met , kindly ask for second opinion if you differ with my review, all the best

**Comment by ogagaoghene** [comment]
@danmainah It is okay. How can I request for an extra review. I have done what you asked that I should do

**Comment by danmainah** [comment]
kindly check on the dashboard, it should offer you option to use the extra reviews

**Comment by ogagaoghene** [comment]
@danmainah I have made the request. Thanks

**Comment by danmainah** [comment]
Hi @ogagaoghene , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Good documentation
✔️ Good descriptions

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ogagaoghene** [comment]
@danmainah Thank you

**Comment by ogagaoghene** [comment]
Fully  resolved and implemented
